[package]
name = "scytheric/fusion"
description = "A forked version of Fusion including new state objects, utility, and much more."
license = "MIT"
authors = ["Elttob", "scytheric"]
version = "0.2.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
